version: '3'
services:
  bune-auth:
    build:
      context: ./apps/servers/bune-auth
      dockerfile: Dockerfile
    ports:
      - "9697:9697" # Cấu hình cổng bạn muốn sử dụng
    env_file:
      - apps/servers/bune-auth/.env # Sử dụng đường dẫn tương đối đến tệp .env
    volumes:
      -./apps/servers/bune-auth:/app
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - auth-domain
  bune-blog:
    # build:
    #   context: ./apps/servers/bune-blog
    #   dockerfile: Dockerfile
    container_name: bune-blog
    image: devhoangkien/bune-blog:latest
    restart: always
    ports:
      - "9698:9698" # Cấu hình cổng bạn muốn sử dụng
    # env_file:
    #   - apps/servers/bune-blog/.env # Sử dụng đường dẫn tương đối đến tệp .env
    environment:
      - APP_PORT=9698
      - DATABASE_URL=postgresql://admin:master123@localhost:5432/bune-blog?schema=public
    volumes:
      - ./apps/servers/bune-blog:/app # Liên kết thư mục nguồn với container
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - blog-domain
  bune-gateway:
    build:
      context: ./apps/servers/bune-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # Cấu hình cổng bạn muốn sử dụng
    env_file:
      - apps/servers/bune-gateway/.env # Sử dụng đường dẫn tương đối đến tệp .env
    volumes:
      - gateway-data:/app # Liên kết thư mục nguồn với container
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - auth-domain
      - blog-domain
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=master123
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:latest
    restart: always
    command: redis-server --save --loglevel warning --requirepass master123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  frontend:
  backend:
  auth-domain:
  blog-domain:
volumes:
  auth-data:
  blog-data:
  gateway-data:
  pg_data:
  redis_data: