version: '3'
services:
  bune-auth:
    build:
      context: ./apps/servers/bune-auth
      dockerfile: Dockerfile
    ports:
      - "9697:9697" # Cấu hình cổng bạn muốn sử dụng
    env_file:
      - apps/servers/bune-auth/.env # Sử dụng đường dẫn tương đối đến tệp .env
    volumes:
      - ./apps/servers/bune-auth:/app # Liên kết thư mục nguồn với container
    depends_on:
      - "auth-db"
      - "cache"
    networks:
      - backend
      - auth-domain
  auth-db:
    image: "postgres:15"
    container_name: "auth-db"
    ports:
      - 5432:5432
    volumes:
      - auth-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "master123"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
    networks:
      - auth-domain
  cache:
    image: "redis:5-alpine"
    container_name: "redis-cache"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
  auth-domain:
volumes:
  auth-data: