version: '3'
services:
  bune-auth:
    build:
      context: ./apps/servers/bune-auth
      dockerfile: Dockerfile
    ports:
      - "9697:9697" # Cấu hình cổng bạn muốn sử dụng
    env_file:
      - apps/servers/bune-auth/.env # Sử dụng đường dẫn tương đối đến tệp .env
    volumes:
      - ./apps/servers/bune-auth:/app # Liên kết thư mục nguồn với container
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - auth-domain
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=master123
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: redis:latest
    restart: always
    command: redis-server --save --loglevel warning --requirepass master123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  frontend:
  backend:
  auth-domain:
volumes:
  auth-data:
  pg_data:
  redis_data: